<?xml version="1.0" encoding="utf-8"?><Database Name="City" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=M-A;Initial Catalog=City;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CityConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bilet" Member="Bilets">
    <Type Name="Bilet">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Pret" Type="System.Decimal" DbType="Decimal(3,2) NOT NULL" CanBeNull="false" />
      <Column Name="Timp" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="Bilet_Bilet" Member="Bilet2" ThisKey="ID" OtherKey="ID" Type="Bilet" Cardinality="One" />
      <Association Name="Bilet_Transport" Member="Transports" ThisKey="ID" OtherKey="BiletID" Type="Transport" />
      <Association Name="Bilet_Bilet" Member="Bilet1" ThisKey="ID" OtherKey="ID" Type="Bilet" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Transport" Member="Transports">
    <Type Name="Transport">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrasID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BiletID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Transport" Member="Transport1" Type="System.String" DbType="VarChar(8) NOT NULL" CanBeNull="false" />
      <Column Name="GMS" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Association Name="Bilet_Transport" Member="Bilet" ThisKey="BiletID" OtherKey="ID" Type="Bilet" IsForeignKey="true" />
      <Association Name="Ora_Transport" Member="Ora" ThisKey="OrasID" OtherKey="ID" Type="Ora" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Judet" Member="Judets">
    <Type Name="Judet">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrasID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Judet" Member="Judet1" Type="System.String" DbType="NVarChar(32) NOT NULL" CanBeNull="false" />
      <Association Name="Ora_Judet" Member="Ora" ThisKey="OrasID" OtherKey="ID" Type="Ora" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Locatie" Member="Locaties">
    <Type Name="Locatie">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrasID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Restaurant" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Scoala" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Institutie" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="Ora_Locatie" Member="Ora" ThisKey="OrasID" OtherKey="ID" Type="Ora" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Oras" Member="Oras">
    <Type Name="Ora">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Oras" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Lat" Type="System.Decimal" DbType="Decimal(12,9)" CanBeNull="true" />
      <Column Name="Long" Type="System.Decimal" DbType="Decimal(12,9)" CanBeNull="true" />
      <Association Name="Ora_Transport" Member="Transports" ThisKey="ID" OtherKey="OrasID" Type="Transport" />
      <Association Name="Ora_Judet" Member="Judets" ThisKey="ID" OtherKey="OrasID" Type="Judet" />
      <Association Name="Ora_Locatie" Member="Locaties" ThisKey="ID" OtherKey="OrasID" Type="Locatie" />
    </Type>
  </Table>
</Database>